// src/tools/**: build-time-only, node-only. Never imported by src/main.ts,
// src/engine/**, or src/render/**.
//
// Every frame is authored as an array of strings, one per row, one character
// per pixel. This is what makes the art reviewable as code: a reviewer sees
// the sprite in the diff instead of an opaque binary. Declaration order below
// is pack order (see atlas-spec.ts), and matches the layout table in
// docs/design/visual-identity.md.
import type { AtlasFrameName } from '../render/atlas.ts';

export type ArtChar = '.' | 'v' | 'n' | 'd' | 'e' | 'b' | 'x';

// '.' is the reserved transparent index (0); the rest map to PALETTE_ORDER (1-6):
// v=void, n=night, d=dusk, e=edge, b=bone, x=lethal.
export const CHAR_TO_INDEX: Record<ArtChar, number> = {
  '.': 0,
  v: 1,
  n: 2,
  d: 3,
  e: 4,
  b: 5,
  x: 6,
};

export interface ArtFrame {
  name: AtlasFrameName;
  /** Pixel offset from the frame's top-left to the entity's AABB top-left. */
  origin: { x: number; y: number };
  rows: readonly string[];
}

// Reused row primitives for the solid-tile dither, written literally per the
// determinism rule: no PRNG anywhere in this package. The lattice repeats
// every 4px so it tiles with no visible join across a 16px tile border.
const EDGE_ROW = 'eeeeeeeeeeeeeeee';
const PLAIN_ROW = 'nnnnnnnnnnnnnnnn';
const DITHER_ROW = 'dnnndnnndnnndnnn';
const TRANS_ROW = '................';

export const ART: readonly ArtFrame[] = [
  {
    name: 'player.idle.0',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
    ],
  },
  {
    // Breathing idle: head and torso dropped 1px versus idle.0.
    name: 'player.idle.1',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
    ],
  },
  {
    // Run stride A: front (right) leg forward and low, back leg trailing.
    name: 'player.run.0',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....bbb..bbb....',
      '....bbb..bbb....',
      '....bbb...bbb...',
      '....bbb...bbb...',
      '....bbb...bbb...',
      '....bbb...bbb...',
      '....bbb....bbb..',
      '....bbb....bbb..',
    ],
  },
  {
    // Run stride B: legs pass through the neutral standing pose.
    name: 'player.run.1',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
    ],
  },
  {
    // Run stride C: mirror of stride A, back (left) leg forward and low.
    name: 'player.run.2',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....bbb..bbb....',
      '....bbb..bbb....',
      '...bbb...bbb....',
      '...bbb...bbb....',
      '...bbb...bbb....',
      '...bbb...bbb....',
      '..bbb....bbb....',
      '..bbb....bbb....',
    ],
  },
  {
    // Run stride D: legs pass through neutral again, completing the 4-frame cycle.
    name: 'player.run.3',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
      '.....bbb.bbb....',
    ],
  },
  {
    // Legs tucked, arms raised; torso widens by 1px each side for the raised arms.
    name: 'player.jump',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbbb....',
      '....ebbbbbbb....',
      '....ebbbbbbb....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '.....bbbbbb.....',
      '.....bbbbbb.....',
      '.....bbbbbb.....',
      '.....bbbbbb.....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  {
    // Legs and arms splayed outward, widening with distance from the torso.
    name: 'player.fall',
    origin: { x: 0, y: 8 },
    rows: [
      '................',
      '................',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '.....ebbbb......',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '..b.ebbbbbb.b...',
      '..b.ebbbbbb.b...',
      '..b.ebbbbbb.b...',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '....ebbbbbb.....',
      '...bbb...bbb....',
      '...bbb...bbb....',
      '..bbb.....bbb...',
      '..bbb.....bbb...',
      '.bbb.......bbb..',
      '.bbb.......bbb..',
      '.bbb........bbb.',
      '.bbb........bbb.',
    ],
  },
  {
    // Lit top surface, then the same dither as tile.solid.fill starting one row lower.
    name: 'tile.solid.top',
    origin: { x: 0, y: 0 },
    rows: [
      EDGE_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
    ],
  },
  {
    // Same 4px dither lattice as tile.solid.top, no lit edge row.
    name: 'tile.solid.fill',
    origin: { x: 0, y: 0 },
    rows: [
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      DITHER_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
    ],
  },
  {
    // 3px plank: the visual top sits at the tile boundary where one-way collision resolves.
    name: 'tile.oneway',
    origin: { x: 0, y: 0 },
    rows: [
      EDGE_ROW,
      PLAIN_ROW,
      PLAIN_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
    ],
  },
  {
    // Four 4px-wide triangles, apex at row 11, full-width base at row 15. The only
    // frame in the atlas that uses lethal: nothing else is ever drawn in this color.
    name: 'hazard.spikes',
    origin: { x: 0, y: 0 },
    rows: [
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      TRANS_ROW,
      '.x...x...x...x..',
      '.xx..xx..xx..xx.',
      'xxx.xxx.xxx.xxx.',
      'xxxxxxxxxxxxxxxx',
      'xxxxxxxxxxxxxxxx',
    ],
  },
  {
    // Edge arch outline, bone interior, open at the bottom (no closing edge row).
    name: 'exit.door',
    origin: { x: 0, y: 0 },
    rows: [
      TRANS_ROW,
      TRANS_ROW,
      '...eeeeeeeeee...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
      '...ebbbbbbbbe...',
    ],
  },
  {
    // Gas lamp: bone body and flame, edge bracket and post. No lethal, ever: this is
    // the player's first encounter with the palette, before red has any meaning yet.
    name: 'title.mark',
    origin: { x: 0, y: 0 },
    rows: [
      '.......ee.......',
      '.......ee.......',
      '......eeee......',
      '.....eeeeee.....',
      '.....ebbbbe.....',
      '.....ebbbbe.....',
      '.....ebbbbe.....',
      '.....ebbbbe.....',
      '.....ebbbbe.....',
      '.....eeeeee.....',
      '.......ee.......',
      '.......ee.......',
      '.......ee.......',
      '......eeee......',
      '.....eeeeee.....',
      '....eeeeeeee....',
    ],
  },
];
